language: cpp
compiler: clang
script: make check -k -j2

sudo: false
before_install:
 - export LLVM=3.7.0
 - export LLVMCONFIG=./clang+llvm-$LLVM-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-config
 - if [ ! -f $LLVMCONFIG ]; then wget -nv -O- http://llvm.org/releases/$LLVM/clang+llvm-$LLVM-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar xJ; fi
