sudo: required
dist: trusty
language: cpp
script: make config=coverage test -k -j2

before_install:
 - export LLVM=3.8.0
 - export LLVMCONFIG=./clang+llvm-$LLVM-rc1-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-config
 - if [ ! -f $LLVMCONFIG ]; then wget -nv -O- http://llvm.org/pre-releases/$LLVM/rc1/clang+llvm-$LLVM-rc1-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar xJ; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
