language: cpp
compiler: clang
script: make test -k -j2

sudo: false
before_install:
 - export LLVM=3.5.1
 - export LLVMCONFIG=./clang+llvm-$LLVM-x86_64-linux-gnu/bin/llvm-config
 - if [ ! -f $LLVMCONFIG ]; then wget -nv -O- http://llvm.org/releases/$LLVM/clang+llvm-$LLVM-x86_64-linux-gnu.tar.xz | tar xJ; fi