<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aike</string>
	</array>
	<key>name</key>
	<string>Aike</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(fn)\s+([A-Za-z0-9_]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.aike</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.aike</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(struct)\s+([A-Za-z0-9_]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.aike</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.aike</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extern|builtin|fn|var|if|else|for|in)\b</string>
			<key>name</key>
			<string>keyword.control.aike</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(not|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.aike</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(void|bool|int|string)\b</string>
			<key>name</key>
			<string>storage.type.aike</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.aike</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9A-Za-z_]*\b</string>
			<key>name</key>
			<string>constant.numeric.aike</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.aike</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.aike</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.aike</string>
	<key>uuid</key>
	<string>D1FD1B52-F137-4FBA-A148-B8A893CD948C</string>
</dict>
</plist>
